//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Labels", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  La Seguridad e Higiene Laboral representan un campo multidisciplinario que tiene por objeto primordial, proteger la vida y preservar la salud y el bienestar de los trabajadores. 
        ///Uno de los aspectos más importantes dentro de las Organizaciones es la Prevención de los Riesgos Laborales, dado que una buena prevención de riesgos, mejora la relación equipo – empresa, creando un vínculo de compromiso que es beneficioso para ambas partes.
        ///Las buenas condiciones del ambiente laboral, aumentan la motivación de lo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AcercaDe_DescripcionAcercaDe {
            get {
                return ResourceManager.GetString("AcercaDe.DescripcionAcercaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asesoramiento externo de Higiene y Seguridad Laboral.
        /// </summary>
        internal static string AcercaDe_TextoAsesoramientoExterno {
            get {
                return ResourceManager.GetString("AcercaDe.TextoAsesoramientoExterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estadística de siniestralidad.
        /// </summary>
        internal static string AcercaDe_TextoAsesoramientoExterno1 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoAsesoramientoExterno1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudios de nivel sonoro.
        /// </summary>
        internal static string AcercaDe_TextoAsesoramientoExterno10 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoAsesoramientoExterno10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudios de niveles lumínicos.
        /// </summary>
        internal static string AcercaDe_TextoAsesoramientoExterno11 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoAsesoramientoExterno11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudios de puesta a tierra y continuidad de las masas.
        /// </summary>
        internal static string AcercaDe_TextoAsesoramientoExterno12 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoAsesoramientoExterno12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudios de vibraciones mano-brazo y cuerpo entero.
        /// </summary>
        internal static string AcercaDe_TextoAsesoramientoExterno13 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoAsesoramientoExterno13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudios de carga térmica.
        /// </summary>
        internal static string AcercaDe_TextoAsesoramientoExterno14 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoAsesoramientoExterno14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigación de accidentes de trabajo.
        /// </summary>
        internal static string AcercaDe_TextoAsesoramientoExterno15 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoAsesoramientoExterno15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrenamiento y capacitación según las necesidades de cada cliente, in situ y a través de plataforma.
        /// </summary>
        internal static string AcercaDe_TextoAsesoramientoExterno16 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoAsesoramientoExterno16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confección de Procedimientos Seguros de Trabajo.
        /// </summary>
        internal static string AcercaDe_TextoAsesoramientoExterno17 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoAsesoramientoExterno17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditorías de diagnóstico en materia de seguridad laboral.
        /// </summary>
        internal static string AcercaDe_TextoAsesoramientoExterno2 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoAsesoramientoExterno2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes de Evacuación y entrenamiento de brigadas de Emergencia a cargo de profesional idóneo.
        /// </summary>
        internal static string AcercaDe_TextoAsesoramientoExterno3 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoAsesoramientoExterno3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realización de evaluaciones de riesgo.
        /// </summary>
        internal static string AcercaDe_TextoAsesoramientoExterno4 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoAsesoramientoExterno4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organización de Comités de Seguridad.
        /// </summary>
        internal static string AcercaDe_TextoAsesoramientoExterno5 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoAsesoramientoExterno5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representación ante inspecciones de Organismos de Contralor.
        /// </summary>
        internal static string AcercaDe_TextoAsesoramientoExterno6 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoAsesoramientoExterno6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programas de Seguridad.
        /// </summary>
        internal static string AcercaDe_TextoAsesoramientoExterno7 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoAsesoramientoExterno7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confección de mapas de riesgos, analizando los riesgos por puestos de trabajo y áreas.
        /// </summary>
        internal static string AcercaDe_TextoAsesoramientoExterno8 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoAsesoramientoExterno8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudios de carga de fuego.
        /// </summary>
        internal static string AcercaDe_TextoAsesoramientoExterno9 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoAsesoramientoExterno9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio.
        /// </summary>
        internal static string AcercaDe_TextoServicio {
            get {
                return ResourceManager.GetString("AcercaDe.TextoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios de Inteligencia Artificial.
        /// </summary>
        internal static string AcercaDe_TextoServicioIA {
            get {
                return ResourceManager.GetString("AcercaDe.TextoServicioIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoreo de seguridad mediante IA en tiempo real..
        /// </summary>
        internal static string AcercaDe_TextoServicioIA1 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoServicioIA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicción y prevención de posibles accidentes..
        /// </summary>
        internal static string AcercaDe_TextoServicioIA10 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoServicioIA10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generación automática de reportes de seguridad..
        /// </summary>
        internal static string AcercaDe_TextoServicioIA11 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoServicioIA11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguimiento inteligente de acciones correctivas..
        /// </summary>
        internal static string AcercaDe_TextoServicioIA12 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoServicioIA12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integración de la IA con la gestión de incidentes, auditorías, capacitaciones y mapas de riesgos..
        /// </summary>
        internal static string AcercaDe_TextoServicioIA13 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoServicioIA13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevención continua de riesgos combinando la supervisión de profesionales de Seguridad e Higiene con IA..
        /// </summary>
        internal static string AcercaDe_TextoServicioIA14 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoServicioIA14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detección automática de actos y condiciones inseguras..
        /// </summary>
        internal static string AcercaDe_TextoServicioIA2 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoServicioIA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detección de incumplimientos en el uso de EPP..
        /// </summary>
        internal static string AcercaDe_TextoServicioIA3 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoServicioIA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detección de ingreso o permanencia en zonas restringidas..
        /// </summary>
        internal static string AcercaDe_TextoServicioIA4 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoServicioIA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación de comportamientos potencialmente peligrosos..
        /// </summary>
        internal static string AcercaDe_TextoServicioIA5 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoServicioIA5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generación de alertas automáticas ante situaciones de riesgo..
        /// </summary>
        internal static string AcercaDe_TextoServicioIA6 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoServicioIA6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoreo inteligente de zonas críticas y maquinaria..
        /// </summary>
        internal static string AcercaDe_TextoServicioIA7 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoServicioIA7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análisis de patrones de comportamiento y situaciones de riesgo..
        /// </summary>
        internal static string AcercaDe_TextoServicioIA8 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoServicioIA8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generación de indicadores inteligentes de seguridad..
        /// </summary>
        internal static string AcercaDe_TextoServicioIA9 {
            get {
                return ResourceManager.GetString("AcercaDe.TextoServicioIA9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina, CABA, Av. Cabildo 123.
        /// </summary>
        internal static string Contacto_Direccion {
            get {
                return ResourceManager.GetString("Contacto.Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion de Protekta.
        /// </summary>
        internal static string Contacto_DireccionTitulo {
            get {
                return ResourceManager.GetString("Contacto.DireccionTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su pagina de contacto..
        /// </summary>
        internal static string Contacto_Encabezado {
            get {
                return ResourceManager.GetString("Contacto.Encabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marketing@protekta.com.
        /// </summary>
        internal static string Contacto_MarketingMail {
            get {
                return ResourceManager.GetString("Contacto.MarketingMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to soporte@protekta.com.
        /// </summary>
        internal static string Contacto_SoporteEmail {
            get {
                return ResourceManager.GetString("Contacto.SoporteEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 425.555.0100.
        /// </summary>
        internal static string Contacto_Telefono {
            get {
                return ResourceManager.GetString("Contacto.Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing:.
        /// </summary>
        internal static string Contacto_TextoMarketing {
            get {
                return ResourceManager.GetString("Contacto.TextoMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soporte:.
        /// </summary>
        internal static string Contacto_TextoSoporte {
            get {
                return ResourceManager.GetString("Contacto.TextoSoporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contratar &gt;.
        /// </summary>
        internal static string Default_BotonContratar {
            get {
                return ResourceManager.GetString("Default.BotonContratar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Seguridad e Higiene Laboral representan un campo multidisciplinario que tiene por objeto primordial, proteger la vida y preservar la salud y el bienestar de los trabajadores. Uno de los aspectos más importantes dentro de las Organizaciones es la Prevención de los Riesgos Laborales, dado que una buena prevención de riesgos, mejora la relación equipo – empresa, creando un vínculo de compromiso que es beneficioso para ambas partes..
        /// </summary>
        internal static string Default_DescripcionEmpresa {
            get {
                return ResourceManager.GetString("Default.DescripcionEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plataforma para gestionar riesgos, incidentes, auditorías, EPP, capacitaciones y acciones correctivas..
        /// </summary>
        internal static string Default_DescripcionGestionDigital {
            get {
                return ResourceManager.GetString("Default.DescripcionGestionDigital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inteligencia Artificial que analiza el entorno operativo, identifica situaciones de riesgo y genera alertas para intervenir antes de que ocurra un accidente..
        /// </summary>
        internal static string Default_DescripcionPrevencionIA {
            get {
                return ResourceManager.GetString("Default.DescripcionPrevencionIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesionales de Higiene y Seguridad + auditorías + mediciones + procedimientos + capacitación..
        /// </summary>
        internal static string Default_DescripcionPrevencionTradicional {
            get {
                return ResourceManager.GetString("Default.DescripcionPrevencionTradicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión digital.
        /// </summary>
        internal static string Default_EncabezadoGestionDigital {
            get {
                return ResourceManager.GetString("Default.EncabezadoGestionDigital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevención inteligente con IA.
        /// </summary>
        internal static string Default_EncabezadoPrevencionIA {
            get {
                return ResourceManager.GetString("Default.EncabezadoPrevencionIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevención tradicional.
        /// </summary>
        internal static string Default_EncabezadoPrevencionTradicional {
            get {
                return ResourceManager.GetString("Default.EncabezadoPrevencionTradicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio de higiene y seguridad.
        /// </summary>
        internal static string Default_EncabezadoPrincipal {
            get {
                return ResourceManager.GetString("Default.EncabezadoPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        internal static string Default_TituloPagina {
            get {
                return ResourceManager.GetString("Default.TituloPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesion.
        /// </summary>
        internal static string Login_BotonLoginTexto {
            get {
                return ResourceManager.GetString("Login.BotonLoginTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilice una cuenta local para iniciar sesión..
        /// </summary>
        internal static string Login_Encabezado {
            get {
                return ResourceManager.GetString("Login.Encabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo de correo electrónico es obligatorio..
        /// </summary>
        internal static string Login_ErrorMensajeValidacionEmail {
            get {
                return ResourceManager.GetString("Login.ErrorMensajeValidacionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo de contraseña es obligatorio..
        /// </summary>
        internal static string Login_ErrorMensajeValidacionPassword {
            get {
                return ResourceManager.GetString("Login.ErrorMensajeValidacionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        internal static string Login_TextoEmail {
            get {
                return ResourceManager.GetString("Login.TextoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string Login_TextoPassword {
            get {
                return ResourceManager.GetString("Login.TextoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse como usuario nuevo.
        /// </summary>
        internal static string Login_TextoRegistrase {
            get {
                return ResourceManager.GetString("Login.TextoRegistrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        internal static string Master_TextoLinkAcercaDe {
            get {
                return ResourceManager.GetString("Master.TextoLinkAcercaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        internal static string Master_TextoLinkContacto {
            get {
                return ResourceManager.GetString("Master.TextoLinkContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string Master_TextoLinkHome {
            get {
                return ResourceManager.GetString("Master.TextoLinkHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        internal static string Master_TextoLinkLogin {
            get {
                return ResourceManager.GetString("Master.TextoLinkLogin", resourceCulture);
            }
        }
    }
}
